### PR TITLE
Profile fields patch - bio and major

### PR DESCRIPTION
**Pull request by z3t1**

### CODE REVIEW

**Comment by vergenzt** [comment]
This doesn't look like it changes the backend model yet. Are you still working on this?

**Comment by z3t1** [comment]
@vergenzt We don't need to change the model. Major and bio are already there. You can test. It works fine and ready to merge.

**Comment by vergenzt** [comment]
Oh! Duh. :) Sorry.

**Comment by vergenzt** [comment]
:+1: to merge

**Pull request merged**
