### PR TITLE
create edit profile page

### PR DESCRIPTION
**Pull request by tyang82**

### CODE REVIEW

**Comment by z3t1** [comment]
@vergenzt @tyang82 I am thinking about just using a `profile/` page. Using some [click-to-edit library](http://vitalets.github.io/x-editable/demo-bs3.html), we can easily merge `profile` and `editProfile` together. To submit, use PUT request (`router.put('/profile', function...)`) . Do you guys wanna me implement this way?

Also, maybe we should make another router for profile. Because literally a user's changing their profile info is not about authentication (`auth.js`).

**Comment by vergenzt** [comment]
(1) I agree, it'd be good to merge them. Honestly Angular might actually be a good choice for the data binding, but we can talk about it more.

(2) Good idea.

**Comment by z3t1** [comment]
@vergenzt You are probably right. [The plugin](https://github.com/vitalets/angular-xeditable) I am looking at actually only has its Angular version under active development. The [jQuery version](https://github.com/vitalets/x-editable) seems [very buggy](https://github.com/vitalets/x-editable/issues). Since we already use Bootstrap, which requires jQuery, we may have to switch to [UI Boostrap](https://angular-ui.github.io/bootstrap/). I am aware that there might be some issues coming up when using Angular and jQuery together.

Since we are doing templating on backend, I don't think we'll write lots of Angular code if we decide to switch over. I'm totally neutral on this choice.

**Comment by vergenzt** [comment]
Since profile editing is due Friday though, it might make sense to merge this if it works and we can change it later.

**Comment by z3t1** [comment]
@vergenzt The current version doesn't work because it doesn't have any backend code. @tyang82 is expecting me to fill the part. I think I can do it tomorrow.

**Comment by vergenzt** [comment]
:+1: We can talk and decide what to do tomorrow then.

**Pull request closed without merging**
