### PR TITLE
Enhance the format of movie search results

### PR DESCRIPTION
**Pull request by tyang82**
changed the format of the movie handlebar so that it displays the poster, description, title, year, and mpaa rating when searching for the movie. If user clicks the movie title, it will take the user to the page where they can comment and rate the movie

### CODE REVIEW

**Comment by vergenzt** [comment]
:+1: The code looks good.

**Comment by vergenzt** [comment]
Could you post a screenshot?

**Comment by z3t1** [comment]
@tyang82 This is good. :+1: Can you remove the `console.log(val);`, which is only for debugging?

Also, for next time, would you like to abandon this branch and try to maintain a clear commit history? :)

**Comment by tyang82** [comment]
@z3t1 sorry! I'll keep that in mind!

**Pull request merged**
