### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by z3t1**
I feel it's necessary to update readme file.

### CODE REVIEW

**Comment by vergenzt** [comment]
:+1:

**Comment by z3t1** [comment]
Wait a sec. I am still editing

**Comment by z3t1** [comment]
Very good. Without these icons, I feel like it's not a real Node.js project.

**Comment by z3t1** [comment]
@vergenzt If you plan to add coverage, we don't have to merge it now.

**Comment by vergenzt** [comment]
Meh. Let's just merge. :) (If you're done)

**Pull request merged**
