### PR TITLE
Write functional tests for M3 and M4

### PR DESCRIPTION
**Pull request by vergenzt**
Working on fleshing out M5, but I thought I'd go ahead and merge the tests. :) With this we can start using [Travis-CI](https://travis-ci.org/) to continuously test our code changes. (And it'll let us know if we break something from a previous milestone!)

### CODE REVIEW

**Comment by z3t1** [comment]
@vergenzt Can you write a Gulp file for these tests? so that everyone can run before pr.

**Comment by vergenzt** [comment]
That was my initial thought, but decided it wasn't really worth it for one task. It runs with `npm test`.

**Comment by z3t1** [comment]
For exhaustive test, particularly for Node.js app, you may want to try some abnormal input, like `null`, `undefined`, `""`, `{}`, `[]`. For now, I'd like to merge it!

**Comment by vergenzt** [comment]
Cool! Yeah I think all the other PRs are failing because the `.travis.yml` file isn't merged yet, so once this gets merged, other PRs should merge from master to get Travis tests passing.

**Pull request merged**
