### PR TITLE
Profile edit feature

### PR DESCRIPTION
**Pull request by z3t1**
I removed all the frontend libraries. @vergenzt Make sure heroku can somehow run `bower install`.

Please have [bower](http://bower.io/) installed (`npm install -g bower`) and run `bower install` before running the website.

I manually copied @tyang82 's code to this branch. So we can safely close that pull request. This one works fine.

There are lots of TODO's in these files (features I haven't implemented, bugs that certainly exist, and potential secure issues). Find and feel free to work on them.

### CODE REVIEW

**Comment by vergenzt** [comment]
> @vergenzt Make sure heroku can somehow run bower install.

Done with #43

**Comment by vergenzt** [comment]
Closing #36 since this subsumes it

**Comment by vergenzt** [comment]
So is this ready to merge?

**Comment by z3t1** [comment]
@vergenzt Yes!

**Comment by vergenzt** [comment]
:+1:

**Pull request merged**
