### PR TITLE
Added a confirm password field on the registration form

### PR DESCRIPTION
**Pull request by egraba3**

### CODE REVIEW

**Comment by z3t1** [comment]
@egraba3 It doesn't give me any warning if they don't match. I can still submit. Can you fix that?

I removed this feature because I had no idea why it didn't work in Modal form.

**Comment by egraba3** [comment]
Huh. When I was testing it on my computer yesterday it would reload the registration page with a "Error: Passwords don't match" warning at the top. I'll take a look

**Comment by z3t1** [comment]
@egraba3 No. I mean if you type two different passwords, you can still submit. The front-end should prevent that by making submit button unclickable.

**Comment by egraba3** [comment]
@z3t1 Ah ok, I'll take a look and try to fix it up

**Comment by egraba3** [comment]
@z3t1 I finally may have gotten it working. It seems to be good to go, at least on my machine. I'm not sure what was so confusing about the data validation package but give it a try and let me know.

**Comment by egraba3** [comment]
@z3t1 

<script type = "text/javascript"> 
          function checkPass() {
            var pass = document.getElementById("inputPassword").value;
            var pass2 = document.getElementById("inputPasswordConfirm").value;
            var messageBox = document.getElementById("confirmMessage");
            var submitButton = document.getElementById("registerSubmitButton");
            if (pass != pass2) {
              messageBox.innerHTML = "Your Passwords do not match!"
              submitButton.disabled = true;
            } else {
              messageBox.innerHTML = "Your Passwords match!"
              submitButton.disabled = false;
             }
          }
</script>

<input type="password" name="inputPassword" data-minlength="6" class="form-control" id="inputPassword" placeholder="Password" required>
            <span class="help-block">Minimum of 6 characters</span>
          </div>
          <div class="form-group">
            <input type="password" class="form-control" name="inputPasswordConfirm" id="inputPasswordConfirm" data-minlength="6" placeholder="Confirm" onkeyup="checkPass()" required>
            <span id="confirmMessage" class="confirmMessage"></span>
            <div class="help-block with-errors"></div>
        </div>
        </div>
          <div class="form-group">
            <button type="submit" id="registerSubmitButton" disabled="disabled" class="btn btn-primary">Submit</button>

No idea why this doesn't work.

**Comment by egraba3** [comment]
@z3t1 I tried putting a little client-side javascript in the main.handlebars to disable the submit button until the password/confirmpassword match. But it still doesn't seem to work. I'm at a loss

Check lines 11-25 and 143-153 in main.handlebars

**Comment by z3t1** [comment]
I will look into it tomorrow or Thursday.

**Comment by z3t1** [comment]
screen shot 2015-07-01 at 10 50 49 am

@egraba3 There is another `#inputPassword` in loginForm. `pass` is empty. Change the id of that element. When you `getElementbyId('inputPassword')`, you get the password of the login form. You may want to learn to debug front-end JS, like set break point, use console, etc.

Also, since we are using [jQuery](https://jquery.com/), would you like to learn how to select HTML node with it? Just to make us have a consistent style.

**Comment by egraba3** [comment]
@z3t1 Wow. I'm so glad you caught that haha. And yeah, I'll rewrite it in jquery and change the id. Thanks!

**Comment by egraba3** [comment]
@z3t1 Ok, now the password confirmation script is done in jquery and seems to be working. Should be good to go (finally)

**Comment by z3t1** [comment]
It's not working on my machine.

**Pull request closed without merging**
